import keybord from '../src/images/FlashSale/keybord.png';

import game from '../src/images/FlashSale/game.png'
export const FlashSale = [
  {
    _id: 1,
    discount: "-40%",
    imgsrc: game,
    description: "Game No 2 Plastict",
    discountPrice: "$120",
    orgPrice: "$120",
    rating: "(88)",
  },
  {
    _id: 2,
    discount: "-40%",
    imgsrc: game,
    description: "HAVIT HV-G92 Gamepad",
    discountPrice: "$120",
    orgPrice: "$120",
    rating: "(88)",
  },
  {
    _id: 3,
    discount: "-40%",
    imgsrc: game,
    description: "Game No 3 Almonitor",
    discountPrice: "$120",
    orgPrice: "$120",
    rating: "(88)",
  },
  {
    _id: 4,
    discount: "-35%",
    imgsrc: game,
    description: "AK-900 Wired Keyboard",
    discountPrice: "$960",
    orgPrice: "$1160",
    rating: "(85)",
  },
  {
    _id: 5,
    discount: "-30%",
    imgsrc: game,
    description: "IPS LCD Gaming Monitor",
    discountPrice: "$370",
    orgPrice: "$400",
    rating: "(99)",
  },
  {
    _id: 6,
    discount: "-35%",
    imgsrc: keybord,
    description: "AK-900 Wired Keyboard",
    discountPrice: "$960",
    orgPrice: "$1160",
    rating: "(85)",
  },
  {
    _id: 7,
    discount: "-30%",
    imgsrc: game,
    description: "IPS LCD Gaming Monitor",
    discountPrice: "$370",
    orgPrice: "$400",
    rating: "(99)",
  },
];
